CEGES/Areas/Analyse/Controllers/PeriodeController.cs
using CEGES_Core;
using CEGES_Core.IRepository;
using CEGES_Core.ViewModels;
using CEGES_Services.IServices;
using CEGES_Util;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace CEGES_MVC.Areas.Analyse.Controllers
{
	[Area("Analyse")]
	[Authorize(Roles = $"{AppConstants.IngenieurRole},{AppConstants.AnalysteRole}")]
	public class PeriodeController : Controller
	{
		private readonly ICegesServices _services;
		private readonly UserManager<ApplicationUser> _userManager;

		public PeriodeController(ICegesServices services, UserManager<ApplicationUser> userManager)
		{
			_services = services;
			_userManager = userManager;
		}

		//Entreprises
		public async Task<IActionResult> IndexAsync()
		{

			var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

			var user = await _userManager.GetUserAsync(User);

			List<ListeEntreprisesVM> vm;

			//check if user is an ANALYSTE
			if (await _userManager.IsInRoleAsync(user, AppConstants.AnalysteRole))
			{

				//return only the entreprises he belongs 
				vm = _services.Configuration.GetAnalysteEntreprisesAndCountsAsync(userId);
				return View(vm);

			}

			//user is a INGENIEUR, returns all entreprises
			vm = _services.Configuration.GetEntreprisesAndCountsAsync();

			return View(vm);
		}


		//Periodes
		public async Task<IActionResult> Liste(int id)
		{

			ListePeriodesVM vm = await _services.Analyse.GetListePeriodesOriginal(id);
			return View(vm);
		}

		public async Task<IActionResult> Details(int entrepriseId, int periodeId)
		{
			ListeMesuresVM vm = await _services.Analyse.GetPeriodeDetails(entrepriseId, periodeId);
			return View(vm);
		}

		//Lorsque clique sur une date non existante, 
		[Authorize(Roles = AppConstants.AnalysteRole)]
		public async Task<IActionResult> Insert(int entrepriseId, DateTime periodeDebut)
		{
			ListeMesuresVM vm = await _services.Analyse.NewPeriodeAsync(entrepriseId, periodeDebut);
			return View("Upsert", vm);
		}


		//Modifier
		[Authorize(Roles = AppConstants.AnalysteRole)]
		public async Task<IActionResult> Update(int entrepriseId, int periodeId)
		{
			ListeMesuresVM vm = await _services.Analyse.GetPeriodeDetails(entrepriseId, periodeId);
			return View("Upsert", vm);
		}

		[HttpPost]
		[Authorize(Roles = AppConstants.AnalysteRole)]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Upsert(ListeMesuresVM vm)
		{
			if (ModelState.IsValid)
			{
				Periode periode = await _services.Analyse.UpsertPeriodeAsync(vm);

				return RedirectToAction(nameof(Details), new
				{
					EntrepriseId = vm.EntrepriseId,
					periodeId = periode.Id
				});
			}
			if (vm.EntrepriseId > 0)
			{
				return View(nameof(Liste), new { id = vm.EntrepriseId });
			}
			else
			{
				return View(nameof(IndexAsync));
			}
		}
	}
}

CEGES/Areas/Configuration/Controllers/EntrepriseController.cs
using CEGES_Core;
using CEGES_Core.ViewModels;
using CEGES_Services.IServices;
using CEGES_Util;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CEGES_MVC.Areas.Configuration.Controllers
{
    [Area("Configuration")]
    [Authorize(Roles = AppConstants.IngenieurRole)]
    public class EntrepriseController : Controller
    {
        private readonly IConfigurationServices _configService;
        private readonly IAnalyseServices _analyseService;

        //Enlevé le wrapper ICegesService, pour faciliter le mocking pour le Testing du controlleur
		public EntrepriseController(IConfigurationServices configService, IAnalyseServices analyseService)
		{
			_configService = configService;
			_analyseService = analyseService;
		}

		public IActionResult Index()
        {
            List<ListeEntreprisesVM> vm = _configService.GetEntreprisesAndCountsAsync();
            return View(vm);
        }

        public async Task<IActionResult> Details(int id)
        {
            DetailEntrepriseVM vm = await _configService.GetEntrepriseDetailAsync(id);

            if (vm.Entreprise == null)
            {
                return NotFound();
            }
            return View(vm);
        }

        // MODIFIER VIEW , NOM ET SELECT LES ANALYSTES
        public async Task<IActionResult> Upsert(int? id)
        {
            UpsertEntrepriseVM vm = new UpsertEntrepriseVM();
            if (id == null)
            {
                vm.Entreprise = new Entreprise();
            } 
            else
            {
                vm.Entreprise = await _configService.GetEntrepriseAsync(id.GetValueOrDefault());
            }
            IEnumerable<ApplicationUser> users = await _analyseService.GetAnalystesListAsync();

            vm.Analystes = users.Select(u => new SelectListItem(u.NormalizedUserName, u.Id, vm.Entreprise.Analystes.Exists(a => a.Id == u.Id))).ToList();

            if (vm.Entreprise == null)
            {
                return NotFound();
            }
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(UpsertEntrepriseVM entrepriseVM)
        {
            if (ModelState.IsValid)
            {
                if (entrepriseVM.Entreprise.Id == 0)
                {
                    await _configService.AddEntrepriseAsync(entrepriseVM.Entreprise);

                }
                else
                {
                    _configService.UpdateEntreprise(entrepriseVM.Entreprise);
                }
                if (entrepriseVM.SelectAnalystes.Count > 3)
                {
                    // Message d'erreur "TROP D'ANALYSTES SÉLECTIONNÉS
                    return RedirectToAction(nameof(Upsert), new { id = entrepriseVM.Entreprise.Id });
                }
                try
                {
                    await _configService.EditAnalystesEntrepriseAsync(entrepriseVM.Entreprise.Id, entrepriseVM.SelectAnalystes);
                }
                catch (Exception)
                {
                    return RedirectToAction(nameof(Upsert), new { id = entrepriseVM.Entreprise.Id });
                }
                return RedirectToAction(nameof(Details), new { id = entrepriseVM.Entreprise.Id });
            }
            return View(entrepriseVM);
        }
    }
}

CEGES/Views/Shared/_DetailInfo.cshtml
@model DetailInfoVM
 
<div class="row">
    <div class="col-md-7 text-right">
        @(Model.Caption)&nbsp;:
    </div>
    <div class="col-md-5 text-left">
        @(Model.Value)
    </div>
</div>

CEGES/Views/Shared/_EquipementConstantDetail.cshtml
@model CEGES_Core.EquipementConstant
@await Html.PartialAsync("_DetailInfo", new DetailInfoVM("Émissions", Model.Emissions.RoundToSignificantDigits(3) + " t/j"))

CEGES/Views/Shared/_EquipementConstantHelp.cshtml
    <div>
        <img src="/images/equipment.png" class="mx-auto d-block" />
        <p>
            Certains équipements ont des émissions constantes peu importe leur utilisation.
        </p>
        <p>
            Par exemple, un bureau administratif ou un système d’éclairage utilisera toujours la même quantité d’énergie par jour ou par mois.
        </p>
        <p>
            Les émissions sont calculées en multipliant la quantité (en tonnes par jour) par la durée de la période à calculer.
        </p>
    </div>

CEGES/Views/Shared/_EquipementConstantUpsert.cshtml
@model CEGES_Core.EquipementConstant

<div class="form-group row">
    <div class="col-4">
        <label asp-for="Nom"></label>
    </div>
    <div class="col-8">
        <input asp-for="Emissions" class="form-control" /> (en tonnes par jour)
        <span asp-validation-for="Emissions" class="text-danger"></span>
    </div>
</div>

CEGES/Views/Shared/_EquipementLineaireDetail.cshtml
@model CEGES_Core.EquipementLineaire
@await Html.PartialAsync("_DetailInfo", new DetailInfoVM("Facteur de conversion", Model.FacteurConversion.RoundToSignificantDigits(3) + " " + Model.UniteMesure))

CEGES/Views/Shared/_EquipementLineaireHelp.cshtml
    <div>
        <img src="/images/equipment.png" class="mx-auto d-block" />
        <p>
            Certains équipements ont des émissions linéaires qui sont directement proportionnelles à leur utilisation.
        </p>
        <p>
            Par exemple, un camion produira toujours la même quantité d’émissions par kilomètre parcouru.
        </p>
        <p>
            Les émissions sont calculées en multipliant le facteur de conversion par l’utilisation de l’équipement durant la période.
        </p>
    </div>

CEGES/Views/Shared/_EquipementLineaireUpsert.cshtml
@model CEGES_Core.EquipementLineaire

<div class="form-group row">
    <div class="col-4">
        <label asp-for="UniteMesure"></label>
    </div>
    <div class="col-8">
        <input asp-for="UniteMesure" class="form-control" />
        <span asp-validation-for="UniteMesure" class="text-danger"></span>
    </div>
</div>
<div class="form-group row">
    <div class="col-4">
        <label asp-for="FacteurConversion"></label>
    </div>
    <div class="col-8">
        <input asp-for="FacteurConversion" class="form-control" /> (en tonnes par <i>unité de mesure</i>)
        <span asp-validation-for="FacteurConversion" class="text-danger"></span>
    </div>
</div>

CEGES/Views/Shared/_EquipementRelatifDetail.cshtml
@model CEGES_Core.EquipementRelatif
@await Html.PartialAsync("_DetailInfo", new DetailInfoVM("Minimum (0%)", Model.Minimum.RoundToSignificantDigits(3) + " t/j"))
@await Html.PartialAsync("_DetailInfo", new DetailInfoVM("Maximum (100%)", Model.Maximum.RoundToSignificantDigits(3) + " t/j"))

CEGES/Views/Shared/_EquipementRelatifHelp.cshtml
    <div>
        <img src="/images/equipment.png" class="mx-auto d-block" />
        <p>
            Certains équipements ont des émissions proportionnelles à l’intensité de leur utilisation.
        </p>
        <p>
            Par exemple, une aluminerie produira toujours une certaine quantité d’émissions même sans être utilisée (à 0% d’intensité), et les émissions augmenteront ensuite proportionnellement jusqu’à l’utilisation maximum de l’aluminerie (à 100% d’intensité).
        </p>
        <p>
            Les émissions (en tonnes par jour) sont calculées en faisant une interpolation (une règle de trois) entre l’émission à intensité nulle et l’émission à intensité maximale selon l’intensité moyenne durant la période. Cette émission moyenne est ensuite multipliée par la durée de la période.
        </p>
    </div>

CEGES/Views/Shared/_EquipementRelatifUpsert.cshtml
@model CEGES_Core.EquipementRelatif

<div class="form-group row">
    <div class="col-4">
        <label asp-for="Minimum"></label>
    </div>
    <div class="col-8">
        <input asp-for="Minimum" class="form-control" /> (en tonnes par jour)
        <span asp-validation-for="Minimum" class="text-danger"></span>
    </div>
</div>
<div class="form-group row">
    <div class="col-4">
        <label asp-for="Maximum"></label>
    </div>
    <div class="col-8">
        <input asp-for="Maximum" class="form-control" /> (en tonnes par jour)
        <span asp-validation-for="Maximum" class="text-danger"></span>
    </div>
</div>

CEGES/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CEGES</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CEGES</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                  <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                      <a class="nav-link text-dark" asp-area="Configuration" asp-controller="Entreprise" asp-action="Index">Configuration</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-dark" asp-area="Analyse" asp-controller="Periode" asp-action="Index">Analyse</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-dark" asp-area="Configuration" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <partial name="_LoginPartial" />
                  </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CEGES - <a asp-area="Configuration" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>