CEGES/Areas/Configuration/Controllers/EntrepriseController.cs
using CEGES_Core;
using CEGES_Core.ViewModels;
using CEGES_Services.IServices;
using CEGES_Util;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CEGES_MVC.Areas.Configuration.Controllers
{
    [Area("Configuration")]
    [Authorize(Roles = AppConstants.IngenieurRole)]
    public class EntrepriseController : Controller
    {
        private readonly IConfigurationServices _configService;
        private readonly IAnalyseServices _analyseService;

        //Enlevé le wrapper ICegesService, pour faciliter le mocking pour le Testing du controlleur
		public EntrepriseController(IConfigurationServices configService, IAnalyseServices analyseService)
		{
			_configService = configService;
			_analyseService = analyseService;
		}

		public IActionResult Index()
        {
            List<ListeEntreprisesVM> vm = _configService.GetEntreprisesAndCountsAsync();
            return View(vm);
        }

        public async Task<IActionResult> Details(int id)
        {
            DetailEntrepriseVM vm = await _configService.GetEntrepriseDetailAsync(id);

            if (vm.Entreprise == null)
            {
                return NotFound();
            }
            return View(vm);
        }

        // MODIFIER VIEW , NOM ET SELECT LES ANALYSTES
        public async Task<IActionResult> Upsert(int? id)
        {
            UpsertEntrepriseVM vm = new UpsertEntrepriseVM();
            if (id == null)
            {
                vm.Entreprise = new Entreprise();
            } 
            else
            {
                vm.Entreprise = await _configService.GetEntrepriseAsync(id.GetValueOrDefault());
            }
            IEnumerable<ApplicationUser> users = await _analyseService.GetAnalystesListAsync();

            vm.Analystes = users.Select(u => new SelectListItem(u.NormalizedUserName, u.Id, vm.Entreprise.Analystes.Exists(a => a.Id == u.Id))).ToList();

            if (vm.Entreprise == null)
            {
                return NotFound();
            }
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(UpsertEntrepriseVM entrepriseVM)
        {
            if (ModelState.IsValid)
            {
                if (entrepriseVM.Entreprise.Id == 0)
                {
                    await _configService.AddEntrepriseAsync(entrepriseVM.Entreprise);

                }
                else
                {
                    _configService.UpdateEntreprise(entrepriseVM.Entreprise);
                }
                if (entrepriseVM.SelectAnalystes.Count > 3)
                {
                    // Message d'erreur "TROP D'ANALYSTES SÉLECTIONNÉS
                    return RedirectToAction(nameof(Upsert), new { id = entrepriseVM.Entreprise.Id });
                }
                try
                {
                    await _configService.EditAnalystesEntrepriseAsync(entrepriseVM.Entreprise.Id, entrepriseVM.SelectAnalystes);
                }
                catch (Exception)
                {
                    return RedirectToAction(nameof(Upsert), new { id = entrepriseVM.Entreprise.Id });
                }
                return RedirectToAction(nameof(Details), new { id = entrepriseVM.Entreprise.Id });
            }
            return View(entrepriseVM);
        }
    }
}

CEGES/Areas/Configuration/Controllers/EquipementController.cs
using CEGES_Core;
using CEGES_Services.IServices;
using CEGES_Util;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Threading.Tasks;

namespace CEGES_MVC.Areas.Configuration.Controllers
{
    [Area("Configuration")]
    [Authorize(Roles = AppConstants.IngenieurRole)]

    public class EquipementController : Controller
    {
        private readonly ICegesServices _services;

        public EquipementController(ICegesServices services)
        {
            _services = services;
        }

        public async Task<IActionResult> Details(int id)
        {
            Equipement equipement = await _services.Configuration.GetEquipementDetailAsync(id);
            if (equipement == null)
            {
                return NotFound();
            }
            return View(equipement);
        }

        public async Task<IActionResult> InsertType(int id)
        {
            Groupe groupe = await _services.Configuration.GetGroupeAsync(id);
            if (groupe == null)
            {
                return NotFound();
            }
            return View(groupe);
        }

        public async Task<IActionResult> Insert(int id, string type)
        {
            Equipement equipement = await _services.Configuration.NewEquipementAsync(id, type);
            if (equipement == null || equipement.Groupe == null)
            {
                return NotFound();
            }
            return View("Upsert", equipement);
        }

        public async Task<IActionResult> Update(int id)
        {
            Equipement equipement = await _services.Configuration.GetEquipementDetailAsync(id);
            if (equipement == null)
            {
                return NotFound();
            }
            return View("Upsert", equipement);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Equipement equipement)
        {
            if (ModelState.IsValid)
            {
                if (equipement.Id == 0)
                {
                    await _services.Configuration.AddEquipementAsync(equipement);
                }
                else
                {
                    _services.Configuration.UpdateEquipement(equipement);
                }
                return RedirectToAction(nameof(Details), new { id = equipement.Id });
            }
            return View(equipement);

        }
    }
}

CEGES/Areas/Configuration/Controllers/GroupeController.cs
using CEGES_Core;
using CEGES_Services.IServices;
using CEGES_Util;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace CEGES_MVC.Areas.Configuration.Controllers
{
    [Area("Configuration")]
    [Authorize(Roles = AppConstants.IngenieurRole)]

    public class GroupeController : Controller
    {
        private readonly ICegesServices _services;

        public GroupeController(ICegesServices services)
        {
            _services = services;
        }

        public async Task<IActionResult> Details(int id)
        {
            Groupe groupe = await _services.Configuration.GetGroupeDetailsAsync(id);
            if (groupe == null)
            {
                return NotFound();
            }
            return View(groupe);
        }

        public async Task<IActionResult> Insert(int id)
        {
            Groupe groupe = await _services.Configuration.NewGroupeAsync(id);
            if (groupe == null)
            {
                return NotFound();
            }
            return View("Upsert", groupe);
        }

        public async Task<IActionResult> Update(int id)
        {
            Groupe groupe = await _services.Configuration.GetGroupeEtEntrepriseAsync(id);
            if (groupe == null)
            {
                return NotFound();
            }
            return View("Upsert", groupe);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Groupe groupe)
        {
            if (ModelState.IsValid)
            {
                if (groupe.Id == 0)
                {
                    await _services.Configuration.AddGroupeAsync(groupe);
                }
                else
                {
                    _services.Configuration.UpdateGroupe(groupe);
                }
                return RedirectToAction(nameof(Details), new { id = groupe.Id });
            }
            return View(groupe);
        }
    }
}

CEGES/Areas/Configuration/Views/Groupe/Details.cshtml
@model Groupe
@{
    ViewData["Title"] = Model.Nom;
}

<h3>
    @Model.Nom
    <small class="text-muted">(Groupe)</small>
</h3>
<div class="row pb-3 backgroundWhite">
    <div class="col-md-4 col-sm-12">
        <a asp-area="Configuration" asp-controller="Groupe" asp-action="Update" asp-route-id="@Model.Id" class="btn btn-secondary w-100">
            <i class="fas fa-plus-circle"></i> &nbsp;Modifier le groupe
        </a>
    </div>
</div>
@{
    <div class="row">
        @foreach (var equipement in Model.Equipements)
        {
            <div class="col mb-4">
                <div class="card h-100" style="min-width: 15rem; max-width: 18rem;">
                    <img src="/images/equipment.png" class="card-img-top rounded"/>
                    <div class="card-body">
                        <p class="card-title h5 text-center"><b style="color:#2c3e50">@equipement.Nom</b></p>
                        <div class="card-block">
                            @await Html.PartialAsync("_DetailInfo", new DetailInfoVM("Type", equipement.Type.GetDisplayName()))
                            @await Html.PartialAsync("_Equipement" + equipement.Type.ToString() + "Detail", equipement)
                        </div>
                    </div>
                    <div class="card-footer text-center">
                        <a asp-controller="Equipement" asp-action="Details" class="card-link" asp-route-id="@equipement.Id">Details</a>
                    </div>
                </div>
            </div>
        }
        <div class="col mb-4">
            <div class="card h-100" style="min-width: 15rem; max-width: 18rem;">
                <img src="/images/equipment.png" class="card-img-top rounded" style="opacity: 0.25" />
                <div class="card-body">
                    <p class="card-title h5 text-center"><b style="color:#2c3e50">&nbsp;</b></p>
                </div>
                <div class="card-footer text-center">
                    <a asp-controller="Equipement" asp-action="InsertType" asp-route-id="@Model.Id" class="btn btn-secondary form-control">Ajouter</a>
                </div>
            </div>
        </div>
    </div>
}
<div class="row pb-3 backgroundWhite">
    <div class="col-4 pb-2 align-items-end">
        <a asp-area="Configuration" asp-controller="Entreprise" asp-action="Details" asp-route-id="@Model.EntrepriseId" class="btn btn-secondary  col-10">
            <i class="fas fa-plus-circle"></i> &nbsp;Retour à @Model.Entreprise.Nom
        </a>
    </div>
</div>

CEGES/Areas/Configuration/Views/Groupe/Upsert.cshtml
@model Groupe
@{
    if (Model.Id == 0)
    {
        ViewData["Title"] = "Ajouter un groupe";
    }
    else
    {
        ViewData["Title"] = "Modifier un groupe";
    }
}

<form method="post" enctype="multipart/form-data" asp-action="Upsert">
    @if (Model.Id != 0)
    {
        <input asp-for="Id" hidden />
    }
    <input asp-for="EntrepriseId" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">@ViewData["Title"]</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Entreprise"></label>
                    </div>
                    <div class="col-8">
                        @Model.Entreprise.Nom
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Nom"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Nom" class="form-control" />
                        <span asp-validation-for="Nom" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        @if (Model.Id != 0)
                        {
                            //update
                            <div class="col">
                                <input type="submit" class="btn btn-info w-100" value="Enregistrer" />
                            </div>
                            <div class="col">
                                <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-secondary  col-10">
                                    <i class="fas fa-plus-circle"></i> &nbsp;Retour
                                </a>
                            </div>
                        }
                        else
                        {
                            //create
                            <div class="col">
                                <input type="submit" onclick="return validateInput()" class="btn btn-primary w-100" value="Ajouter" />
                            </div>
                            <div class="col">
                                <a asp-controller="Entreprise" asp-action="Details" asp-route-id="@Model.EntrepriseId" class="btn btn-secondary  col-10">
                                    <i class="fas fa-plus-circle"></i> &nbsp;Retour
                                </a>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>